import './globals.css'

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-conic-gradient'>
        <nav>
          <h1 className='bg-black text-white p-6 '>Navbar</h1>
        </nav>

        {children}
      </body>
    </html>
  );
}
