import './globals.css'
import { Providers } from './providers';
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en" className='dark'>
      <body>
        <Providers>

        <nav>
          <h1 className='bg-slate-300 text-black p-6 '>Navbar</h1>
        </nav>

        {children}
        <footer className='bg-slate-300 text-black p-6'>Footer</footer>
        </Providers>
      </body>
    </html>
  );
}
