import './globals.css'
import { Providers } from './providers';
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en" className='dark'>
      <body>
        <Providers>

        <nav>
          <h1 className='bg-black text-white p-6 '>Navbar</h1>
        </nav>

        {children}
        </Providers>
      </body>
    </html>
  );
}
